apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/kubeflow/pipelines//manifests/kustomize/base?ref=0.5.1

resources:
  # use a custom podTemplate definition for tensorboard viewer
  # -> points tensorflow logs to a S3 endpoint
  - manifest/viewer-tensorboard-template-configmap.yaml
  # this configmap overwrites the default configs for ml-pipeline api server
  - manifest/ml-pipeline-apiserver-configmap.yaml
  # mysql database used by ml-pipeline api server and metadata server
  - manifest/mysql.yaml

namespace: kubeflow

patchesStrategicMerge:
  - aws-configurations-patch.yaml

configMapGenerator:
  # Note: pipeline-install-config is used by official kubeflow for installation parameters.
  # See: https://github.com/kubeflow/pipelines/blob/0.5.1/manifests/kustomize/base/kustomization.yaml
  # Create your own if you want to overwrite those parameters
  - name: pipeline-aws-parameters
    env: params.env    # All parameters can be set inside this file
  # Modified docker entrypoint so that multiple databases can be created on
  # startup (pipeline db, metadata db, cache db)
  # Ref: https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh
  - name: mysql-configs
    files:
    - assets/docker-entrypoint.sh

secretGenerator:
  # Please update the secret here
  - name: mysql-secret
    behavior: replace
    env: mysql.env

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: awsRegion
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.awsRegion
  - name: artifactRepositoryBucket
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryBucket
  - name: artifactRepositoryKeyPrefix
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.artifactRepositoryKeyPrefix
  - name: pipelineBucket
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.pipelineBucket
  - name: pipelinePath
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.pipelinePath
  - name: mysqlPvcName
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.mysqlPvcName
  - name: mysqlStorageClass
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.mysqlStorageClass
  - name: mysqlStorageType
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.mysqlStorageType
  - name: mysqlStorageSize
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.mysqlStorageSize
  - name: groupConcatMaxLen
    objref:
      kind: ConfigMap
      name: pipeline-aws-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.groupConcatMaxLen

configurations:
  - params.yaml